security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        chain_provider:
            chain:
                providers: [app_student_provider, app_teacher_provider]
        app_student_provider:
            entity:
                class: App\Entity\Student
                property: email
        app_teacher_provider:
            entity:
                class: App\Entity\Teacher
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: chain_provider
            guard:
                authenticators:
                    - App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/filldb, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
